[project]
name = "museum-quiz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "environs>=14.5.0",
    "redis>=7.0.1",
    "vkbottle>=4.6.2",
]
